org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

GROUP=io.github.androidpoet
VERSION_NAME=0.1.0

POM_DESCRIPTION=Kotlin Multiplatform SDK for Dodo Payments
POM_URL=https://github.com/AndroidPoet/dodopayments-kmp
POM_SCM_URL=https://github.com/AndroidPoet/dodopayments-kmp
POM_SCM_CONNECTION=scm:git:git://github.com/AndroidPoet/dodopayments-kmp.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/AndroidPoet/dodopayments-kmp.git

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=androidpoet
POM_DEVELOPER_NAME=Ranbir Singh
POM_DEVELOPER_URL=https://github.com/AndroidPoet

SONATYPE_HOST=DEFAULT
RELEASE_SIGNING_ENABLED=true
